### ISSUE TITLE
test host device

### ISSUE THREAD

**Issue by vysocky** [matthiasdiener/omptest#2]
Hi @matthiasdiener,
thank you for your GCC offloading compilation script. It helped me a lot. I am testing the offloading now, but I don't understand part of your test application. 
https://github.com/matthiasdiener/omptest/blob/403e28da741ab9dc42c93cfbed468e4d9428e920/HybridOMP.C#L35-L50

- Let say you have _N_ devices available. The loop just says that you offload the code _N_ times, but you don't specify to which device to offload, so probably it will be offloaded always to the same device. Am I right?
- [Specification](https://www.openmp.org/spec-html/5.0/openmpsu149.html) says that `omp_is_initial_device()` returns true (despite it is int) if the task is executed at a host device. You increment `num_gpus` if the function returns 0 (false), and then at line 49 you say that offloading is possible if the `num_gpus > 0` .
- The condition at line 48 is the same as the condition at the following line, so there is a dead code.

I hope you get my point.

When executing your test application `omp_is_initial_device()` always returns 0. `ldd` confirms, that the binary is linked with the libraries from the GCC (GCC-10.2.0 or GCC-7.3.0 + CUDA/10.2.89) I have compiled (libstdc++.so, libgomp.so, libgcc_s.so). Do you have an idea could be wrong?

Thank you.
Ondra

**Comment by matthiasdiener** [comment]
> https://github.com/matthiasdiener/omptest/blob/403e28da741ab9dc42c93cfbed468e4d9428e920/HybridOMP.C#L35-L50
> 
> * Let say you have _N_ devices available. The loop just says that you offload the code _N_ times, but you don't specify to which device to offload, so probably it will be offloaded always to the same device. Am I right?

Yes, you're right, the code is incorrect. Line 38 should be

```c
#pragma omp target device(i)
```

> * [Specification](https://www.openmp.org/spec-html/5.0/openmpsu149.html) says that `omp_is_initial_device()` returns true (despite it is int) if the task is executed at a host device. You increment `num_gpus` if the function returns 0 (false), and then at line 49 you say that offloading is possible if the `num_gpus > 0` .

I think this works as it should. If `omp_is_initial_device()` returns false, i.e. `A[0]==0`, we know the code was executed on a GPU, and `num_gpus` is incremented.

> * The condition at line 48 is the same as the condition at the following line, so there is a dead code.

I'm not exactly sure what you mean here, but line 48 should probably be removed, so that the status message is always printed.

> I hope you get my point.
> 
> When executing your test application `omp_is_initial_device()` always returns 0. `ldd` confirms, that the binary is linked with the libraries from the GCC (GCC-10.2.0 or GCC-7.3.0 + CUDA/10.2.89) I have compiled (libstdc++.so, libgomp.so, libgcc_s.so). Do you have an idea could be wrong?

Not sure, maybe it is picking the wrong libraries (or library versions)? Maybe try checking with `nvprof` whether any code is executed on a device. Also, make sure you can run CUDA code correctly.

**Comment by vysocky** [comment]
My problem was in misunderstanding the return value of the `omp_is_initial_device()`. The code works fine now, thanks!
